
- name: CloudEngine command test
  hosts: officeswitch
  vars:
    ansible_host_key_checking: false
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: community.network.ce
    ansible_user: admin
    ansible_password: VNS@Admin@15

  tasks:
  - name: "Run display version on remote devices"
    remote_user: huawei
    community.network.ce_command:
      commands: display version
