
- name: CloudEngine command test
  hosts: huawei
  vars:
    ansible_host_key_checking: false

  tasks:
  - name: "Run display version on remote devices"
    community.network.ce_command:
      commands: display version
